# Control Systems 2, Coding Exercise 07: Vector and Signal Norms,
2024 ETH Zurich, Niclas Scheuer, Roy Werder, Dejan Milojevic; Institute for Dynamic Systems and Control; Prof. Emilio Frazzoli

We wish you a nice time when solving this notebook. Authors:

- Niclas Scheuer; nscheuer@ethz.ch
- Roy Werder; werderr@ethz.ch

# Setup:

## Installing the required packages:

In [48]:
!pip install cs2solutions --upgrade


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


## Import packages:
The following piece of code will import the packages that will be used in the code. Take note of the chosen shortcuts. If you have no experience with the [NumPy](https://numpy.org/) library, read the documentation and do some tutorials. It is very important for matrix operations in Python.

In [49]:
from cs2solutions import discretization, morse

#TODO: remove imports
from typing import Optional, List, Tuple
import numpy as np
import matplotlib.pyplot as plt
import control as ct
from scipy import signal as sig
from scipy.signal import butter, lfilter

## Plotting functions:
Name the plotting fcts


--------
Filler text: Some funny project for the student

--------
## Exercise 1a:

Please complete the following function to calculate the 2-norm and infinity-norm of a vector.

$||x||_2 = \sqrt{\Sigma_i |x_i|^2}$

$||x||_{\infty} = \max{|x_i|}$

In [50]:
def vector2norm(vector: np.ndarray) -> float:
    """
    Calculate the 2-norm (Euclidean norm) of a NumPy array.

    Parameters:
    vector (np.ndarray): Input array for which 2-norm is to be calculated.

    Returns:
    float: The 2-norm of the input array.
    """
    if len(vector) == 0 or vector is None or not isinstance(vector, np.ndarray):
        raise ValueError("Input vector is invalid")
    
    squared_sum = 0.0
    for elem in vector:
        squared_sum += elem**2
    norm = np.sqrt(squared_sum)

    return norm

In [51]:
def vectorInfnorm(vector: np.ndarray) -> float:
    """
    Calculate the infinity-norm (maximum absolute value) of a NumPy array.

    Parameters:
    vector (np.ndarray): Input array for which infinity-norm is to be calculated.

    Returns:
    float: The infinity-norm of the input array.
    """
    if len(vector) == 0 or vector is None or not isinstance(vector, np.ndarray):
        raise ValueError("Input vector is invalid")
    
    max_elem = 0.0
    for elem in vector:
        if abs(elem) > max_elem:
            max_elem = abs(elem)

    return max_elem

## Exercise 1b

Below you find an outline for the p-norm of a vector. Please complete the function.

$||x||_p = (\Sigma_i |x_i|^p)^{\frac{1}{p}}$

In [52]:
def vectorPnorm(vector: np.ndarray, p: float) -> float:
    """
    Calculate the infinity-norm (maximum absolute value) of a NumPy array.

    Parameters:
    vector (np.ndarray): Input array for which infinity-norm is to be calculated.

    Returns:
    float: The infinity-norm of the input array.
    """
    if len(vector) == 0 or vector is None or not isinstance(vector, np.ndarray):
        raise ValueError("Input vector is invalid")

    if p is None:
        return vector2norm(vector)

    p = float(p)
    if not isinstance(p, float) or p <= 0.0:
        raise ValueError("p must be a positive integer")

    norm_sum = 0.0
    for elem in vector:
        norm_sum += abs(elem)**p
    
    return norm_sum**(1/p)

Complete the small adjustments needed to make 'vectorPnorm(vector, p)' also work with floating-point variables 'p'.

Implement error-handling and exceptions to account for empty inputs! For example, if no p is given, calculate a default norm or throw an error.

Test your code below :D

In [53]:
array = np.array([1, 2, 3, 4, 5])
norm2 = vector2norm(array)
norm3 = vectorPnorm(array, 3)
norm3_5 = vectorPnorm(array, 3.5)
norm4 = vectorPnorm(array, 4)

print(f"2-norm of {array} is {norm2}\n")
print(f"3-norm of {array} is {norm3}\n")
print(f"3.5-norm of {array} is {norm3_5}\n")
print(f"4-norm of {array} is {norm4}\n")
print(f"Inf-norm of {array} is {vectorInfnorm(array)}\n")

2-norm of [1 2 3 4 5] is 7.416198487095663

3-norm of [1 2 3 4 5] is 6.082201995573399

3.5-norm of [1 2 3 4 5] is 5.788317364864018

4-norm of [1 2 3 4 5] is 5.593654949523078

Inf-norm of [1 2 3 4 5] is 5



--------
## Exercise 2a:

Fill out the code for the following matrix norms:

$||G||_F = \sqrt{\Sigma_{i,j}|g_{ij}|^2}=\sqrt{tr(G^*G)}$

$||G||_{max} = \max{|g_{ij}|}$

$||G||_{i,2} = \sqrt{\rho(G^*G)} = \sqrt{|\lambda_{max}(G^*G)|} = \overline{\sigma}(G)$

$||G||_{i,P} = \max_{\omega \neq 0}{\frac{||G\omega||_p}{||\omega||_p}} = \max_{||\omega||_p=1}{||G\omega||_p}$

$||G||_{i,\infty} = max_i{\Sigma_j |g_{ij}|}$

In [54]:
def matrixFrnorm(matrix: np.ndarray) -> float:
     """
     Calculate the Frobenius norm of a matrix manually.

     Parameters:
     matrix (numpy.ndarray): Input matrix for which the Frobenius norm is to be calculated.

     Returns:
     float: The Frobenius norm of the input matrix.
     """
     if matrix is None or not isinstance(matrix, np.ndarray):
        raise ValueError("Input matrix is invalid")
     
     squared_sum = 0.0
     for row in matrix:
          for elem in row:
               squared_sum += elem**2
     
     return np.sqrt(squared_sum)

In [55]:
def matrixMaxrnorm(matrix: np.ndarray) -> float:
     """
     Calculate the maximum norm of a matrix manually.

     Parameters:
     matrix (numpy.ndarray): Input matrix for which the maximum norm is to be calculated.

     Returns:
     float: The maximum norm of the input matrix.
     """
     if matrix is None or not isinstance(matrix, np.ndarray):
        raise ValueError("Input matrix is invalid")

     max_elem = 0.0
     for row in matrix:
          for elem in row:
               if abs(elem) > max_elem:
                    max_elem = abs(elem)

     return max_elem

In [56]:
def matrix2norm(matrix: np.ndarray) -> float:
    """
    Calculate the 2-norm of a matrix manually.

    Parameters:
    matrix (numpy.ndarray): Input matrix for which the 2-norm is to be calculated.

    Returns:
    float: The 2-norm of the input matrix.
    """
    if matrix is None or not isinstance(matrix, np.ndarray):
        raise ValueError("Input matrix is invalid")

    product_matrix = np.dot(matrix.T, matrix)
    eigenvalues, _ = np.linalg.eig(product_matrix)
    max_eigenvalue = np.max(eigenvalues)
    norm = np.sqrt(max_eigenvalue)
    return norm

In [57]:
def matrixPnorm(matrix: np.ndarray, p: float) -> float:
    """
    Calculate the p-norm of a matrix manually.

    Parameters:
    matrix (numpy.ndarray): Input matrix for which the p-norm is to be calculated.

    Returns:
    float: The p-norm of the input matrix.
    """
    if matrix is None or not isinstance(matrix, np.ndarray):
        raise ValueError("Input matrix is invalid")
    if p is None:
        return matrix2norm(matrix)
    p = float(p)
    if not isinstance(p, float) or p <= 0.0:
        raise ValueError("p must be a positive integer")

    singular_values = calculate_matrix_singular_values(matrix)
    norm = np.sum(np.abs(singular_values)**p)**(1.0/p)
    return norm

def calculate_matrix_singular_values(matrix: np.ndarray) -> np.ndarray:
    """
    Calculate the singular values of a matrix manually.

    Parameters:
    matrix (numpy.ndarray): Input matrix for which the singular values are to be calculated.

    Returns:
    numpy.ndarray: The singular values of the input matrix.
    """
    if matrix is None or not isinstance(matrix, np.ndarray):
        raise ValueError("Input matrix is invalid")

    product_matrix = np.dot(matrix.T, matrix) if matrix.shape[0] > matrix.shape[1] else np.dot(matrix, matrix.T)
    eigenvalues, _ = np.linalg.eig(product_matrix)
    singular_values = np.sqrt(np.abs(eigenvalues))
    return singular_values

In [58]:
def matrixInfnorm(matrix: np.ndarray) -> float:
    """
    Calculate the infinity-norm of a matrix manually.

    Parameters:
    matrix (numpy.ndarray): Input matrix for which the infinity-norm is to be calculated.

    Returns:
    float: The infinity-norm of the input matrix.
    """
    if matrix is None or not isinstance(matrix, np.ndarray):
        raise ValueError("Input matrix is invalid")

    row_sums = np.sum(np.abs(matrix), axis=1)  # Calculate absolute row sums
    norm = np.max(row_sums)  # Take the maximum of the absolute row sums
    return norm

--------
## Exercise 2b:

Test out the norms for some matrices!

In [59]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

normF = matrixFrnorm(matrix)
normMax = matrixMaxrnorm(matrix)
norm2 = matrix2norm(matrix)
norm3 = matrixPnorm(matrix, 3)
norm3_5 = matrixPnorm(matrix, 3.5)
norm4 = matrixPnorm(matrix, 4)
normInf = matrixInfnorm(matrix)

print(f"Frobenius norm of \n {matrix} is {normF}\n")
print(f"Max norm of \n {matrix} is {normMax}\n")
print(f"2-norm of \n {matrix} is {norm2}\n")
print(f"3-norm of \n {matrix} is {norm3}\n")
print(f"3.5-norm of \n {matrix} is {norm3_5}\n")
print(f"4-norm of \n {matrix} is {norm4}\n")
print(f"Inf-norm of \n {matrix} is {normInf}\n")

Frobenius norm of 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] is 16.881943016134134

Max norm of 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] is 9

2-norm of 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] is 16.848103352614213

3-norm of 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] is 16.849535224829065

3.5-norm of 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] is 16.84841243172686

4-norm of 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] is 16.84817145624563

Inf-norm of 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] is 24



-------
## Exercise 3:

Now that you have completed the manual way of solving norms, this last exercise should show you the easier way of doing it. We will mostly use numpy, especially the [numpy.linalg.norm()](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html) function.

In [60]:
def vector2norm_numpy(vector):
    return np.linalg.norm(vector, ord=2)

def vectorInfnorm_numpy(vector):
    return np.linalg.norm(vector, ord=np.inf)

def vectorPnorm_numpy(vector, p):
    return np.linalg.norm(vector, ord=p)



In [61]:
norm2_numpy = vector2norm_numpy(array)
norm3_numpy = vectorPnorm_numpy(array, 3)
norm3_5_numpy = vectorPnorm_numpy(array, 3.5)
norm4_numpy = vectorPnorm_numpy(array, 4)

print(f"2-norm of {array} is {norm2_numpy}\n")
print(f"3-norm of {array} is {norm3_numpy}\n")
print(f"3.5-norm of {array} is {norm3_5_numpy}\n")
print(f"4-norm of {array} is {norm4_numpy}\n")
print(f"Inf-norm of {array} is {vectorInfnorm_numpy(array)}\n")

2-norm of [1 2 3 4 5] is 7.416198487095663

3-norm of [1 2 3 4 5] is 6.082201995573399

3.5-norm of [1 2 3 4 5] is 5.788317364864018

4-norm of [1 2 3 4 5] is 5.593654949523078

Inf-norm of [1 2 3 4 5] is 5.0



In [62]:
def matrixFrnorm_numpy(matrix):
    return np.linalg.norm(matrix, ord='fro')

def matrixMaxrnorm_numpy(matrix):
    return np.max(matrix)

def matrix2norm_numpy(matrix):
    return np.linalg.norm(matrix, ord=2)

def matrixInfnorm_numpy(matrix):
    return np.linalg.norm(matrix, ord=np.inf)

In [63]:
normF_numpy = matrixFrnorm_numpy(matrix)
normMax_numpy = matrixMaxrnorm_numpy(matrix)
norm2_numpy = matrix2norm_numpy(matrix)
normInf_numpy = matrixInfnorm_numpy(matrix)

print(f"Frobenius norm of \n {matrix} is {normF_numpy}\n")
print(f"Max norm of \n {matrix} is {normMax_numpy}\n")
print(f"2-norm of \n {matrix} is {norm2_numpy}\n")
print(f"Inf-norm of \n {matrix} is {normInf_numpy}\n")

Frobenius norm of 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] is 16.881943016134134

Max norm of 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] is 9

2-norm of 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] is 16.84810335261421

Inf-norm of 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] is 24.0



However, it is also apparent that for matrices you can no longer use the general form of the P-norm as well as the max norm, since those are unsupported in numpy.linalg for matrices