-------

## Python Libraries

We use the following Python libraries which need to be imported. If you have no experience with the [NumPy](https://numpy.org/) library, read the documentation and do some tutorials. It is very important for matrix operations in Python.

In [15]:
# Install the required python library with pip
!pip install control


[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: C:\Users\nicla\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


-------

## Installation
We use the [Python library](https://python-control.readthedocs.io/en/0.9.3.post2/) `control`, which can be installed using `pip`. If you have no experience with Python, try to do some tutorials (e.g. check [this](https://docs.python.org/3/tutorial/) one). The same goes for installing Python packages using `pip`, see this [tutorial](https://packaging.python.org/en/latest/tutorials/installing-packages/). There are plenty of other Python tutorials for beginners if you do a Google/YouTube search.

If you have done all the Jupyter Notebooks leading up to this one, you should have all the necessary libraries installed. 


In [16]:
# Import the required python libraries
from typing import Optional, List, Tuple
import numpy as np
import matplotlib.pyplot as plt
import control as ct

--------
Filler text: Some funny project for the student

--------
## Exercise 1a:

Please complete the following function to calculate the 2-norm and infinity-norm of a vector.

$||x||_2 = \sqrt{\Sigma_i |x_i|^2}$

$||x||_{\infty} = \max{|x_i|}$

In [17]:
def vector2norm(vector: np.ndarray) -> float:
    """
    Calculate the 2-norm (Euclidean norm) of a NumPy array.

    Parameters:
    vector (np.ndarray): Input array for which 2-norm is to be calculated.

    Returns:
    float: The 2-norm of the input array.
    """
    if len(vector) == 0 or vector is None or not isinstance(vector, np.ndarray):
        raise ValueError("Input vector is invalid")
    
    squared_sum = 0.0
    for elem in vector:
        squared_sum += elem**2
    norm = np.sqrt(squared_sum)

    return norm

In [18]:
def vectorInfnorm(vector: np.ndarray) -> float:
    """
    Calculate the infinity-norm (maximum absolute value) of a NumPy array.

    Parameters:
    vector (np.ndarray): Input array for which infinity-norm is to be calculated.

    Returns:
    float: The infinity-norm of the input array.
    """
    if len(vector) == 0 or vector is None or not isinstance(vector, np.ndarray):
        raise ValueError("Input vector is invalid")
    
    max_elem = 0.0
    for elem in vector:
        if abs(elem) > max_elem:
            max_elem = abs(elem)

    return max_elem

## Exercise 1b

Below you find an outline for the p-norm of a vector. Please complete the function.

$||x||_p = (\Sigma_i |x_i|^p)^{\frac{1}{p}}$

In [19]:
def vectorPnorm(vector: np.ndarray, p: float) -> float:
    """
    Calculate the infinity-norm (maximum absolute value) of a NumPy array.

    Parameters:
    vector (np.ndarray): Input array for which infinity-norm is to be calculated.

    Returns:
    float: The infinity-norm of the input array.
    """
    if len(vector) == 0 or vector is None or not isinstance(vector, np.ndarray):
        raise ValueError("Input vector is invalid")

    if p is None:
        return vector2norm(vector)

    p = float(p)
    if not isinstance(p, float) or p <= 0.0:
        raise ValueError("p must be a positive integer")

    norm_sum = 0.0
    for elem in vector:
        norm_sum += abs(elem)**p
    
    return norm_sum**(1/p)

Complete the small adjustments needed to make 'vectorPnorm(vector, p)' also work with floating-point variables 'p'.

Implement error-handling and exceptions to account for empty inputs! For example, if no p is given, calculate a default norm or throw an error.

Test your code below :D

In [20]:
array = np.array([1, 2, 3, 4, 5])
norm2 = vector2norm(array)
norm3 = vectorPnorm(array, 3)
norm3_5 = vectorPnorm(array, 3.5)
norm4 = vectorPnorm(array, 4)

print(f"2-norm of {array} is {norm2}")
print(f"3-norm of {array} is {norm3}")
print(f"3.5-norm of {array} is {norm3_5}")
print(f"4-norm of {array} is {norm4}")
print(f"Inf-norm of {array} is {vectorInfnorm(array)}")

2-norm of [1 2 3 4 5] is 7.416198487095663
3-norm of [1 2 3 4 5] is 6.082201995573399
3.5-norm of [1 2 3 4 5] is 5.788317364864018
4-norm of [1 2 3 4 5] is 5.593654949523078
Inf-norm of [1 2 3 4 5] is 5


--------
## Exercise 2a:

Fill out the code for the following matrix norms:

$||G||_F = \sqrt{\Sigma_{i,j}|g_{ij}|^2}=\sqrt{tr(G^*G)}$

$||G||_{max} = \max{|g_{ij}|}$

$||G||_{i,2} = \sqrt{\rho(G^*G)} = \sqrt{|\lambda_{max}(G^*G)|} = \overline{\sigma}(G)$

$||G||_{i,P} = \max_{\omega \neq 0}{\frac{||G\omega||_p}{||\omega||_p}} = \max_{||\omega||_p=1}{||G\omega||_p}$

$||G||_{i,\infty} = max_i{\Sigma_j |g_{ij}|}$

In [29]:
def matrixFrnorm(matrix: np.ndarray) -> float:
     """
     Calculate the Frobenius norm of a matrix manually.

     Parameters:
     matrix (numpy.ndarray): Input matrix for which the Frobenius norm is to be calculated.

     Returns:
     float: The Frobenius norm of the input matrix.
     """
     if matrix is None or not isinstance(matrix, np.ndarray):
        raise ValueError("Input matrix is invalid")
     
     squared_sum = 0.0
     for row in matrix:
          for elem in row:
               squared_sum += elem**2
     
     return np.sqrt(squared_sum)

In [27]:
def matrixMaxrnorm(matrix: np.ndarray) -> float:
     """
     Calculate the maximum norm of a matrix manually.

     Parameters:
     matrix (numpy.ndarray): Input matrix for which the maximum norm is to be calculated.

     Returns:
     float: The maximum norm of the input matrix.
     """
     if matrix is None or not isinstance(matrix, np.ndarray):
        raise ValueError("Input matrix is invalid")

     max_elem = 0.0
     for row in matrix:
          for elem in row:
               if abs(elem) > max_elem:
                    max_elem = abs(elem)

     return max_elem

In [23]:
def matrix2norm(matrix: np.ndarray) -> float:
    """
    Calculate the 2-norm of a matrix manually.

    Parameters:
    matrix (numpy.ndarray): Input matrix for which the 2-norm is to be calculated.

    Returns:
    float: The 2-norm of the input matrix.
    """
    if matrix is None or not isinstance(matrix, np.ndarray):
        raise ValueError("Input matrix is invalid")

    product_matrix = np.dot(matrix.T, matrix)
    eigenvalues, _ = np.linalg.eig(product_matrix)
    max_eigenvalue = np.max(eigenvalues)
    norm = np.sqrt(max_eigenvalue)
    return norm

In [24]:
def matrixPnorm(matrix: np.ndarray, p: float) -> float:
    """
    Calculate the p-norm of a matrix manually.

    Parameters:
    matrix (numpy.ndarray): Input matrix for which the p-norm is to be calculated.

    Returns:
    float: The p-norm of the input matrix.
    """
    if matrix is None or not isinstance(matrix, np.ndarray):
        raise ValueError("Input matrix is invalid")
    if p is None:
        return matrix2norm(matrix)
    p = float(p)
    if not isinstance(p, float) or p <= 0.0:
        raise ValueError("p must be a positive integer")

    singular_values = calculate_matrix_singular_values(matrix)
    norm = np.sum(np.abs(singular_values)**p)**(1.0/p)
    return norm

def calculate_matrix_singular_values(matrix: np.ndarray) -> np.ndarray:
    """
    Calculate the singular values of a matrix manually.

    Parameters:
    matrix (numpy.ndarray): Input matrix for which the singular values are to be calculated.

    Returns:
    numpy.ndarray: The singular values of the input matrix.
    """
    if matrix is None or not isinstance(matrix, np.ndarray):
        raise ValueError("Input matrix is invalid")

    product_matrix = np.dot(matrix.T, matrix) if matrix.shape[0] > matrix.shape[1] else np.dot(matrix, matrix.T)
    eigenvalues, _ = np.linalg.eig(product_matrix)
    singular_values = np.sqrt(np.abs(eigenvalues))
    return singular_values

In [25]:
def matrixInfnorm(matrix: np.ndarray) -> float:
    """
    Calculate the infinity-norm of a matrix manually.

    Parameters:
    matrix (numpy.ndarray): Input matrix for which the infinity-norm is to be calculated.

    Returns:
    float: The infinity-norm of the input matrix.
    """
    if matrix is None or not isinstance(matrix, np.ndarray):
        raise ValueError("Input matrix is invalid")

    row_sums = np.sum(np.abs(matrix), axis=1)  # Calculate absolute row sums
    norm = np.max(row_sums)  # Take the maximum of the absolute row sums
    return norm

--------
## Exercise 2b:

Test out the norms for some matrices!

In [30]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

normF = matrixFrnorm(matrix)
normMax = matrixMaxrnorm(matrix)
norm2 = matrix2norm(matrix)
norm3 = matrixPnorm(matrix, 3)
norm3_5 = matrixPnorm(matrix, 3.5)
norm4 = matrixPnorm(matrix, 4)
normInf = matrixInfnorm(matrix)

print(f"Frobenius norm of {matrix} is {normF}")
print(f"Max norm of {matrix} is {normMax}")
print(f"2-norm of {matrix} is {norm2}")
print(f"3-norm of {matrix} is {norm3}")
print(f"3.5-norm of {matrix} is {norm3_5}")
print(f"4-norm of {matrix} is {norm4}")
print(f"Inf-norm of {matrix} is {normInf}")

Frobenius norm of [[1 2 3]
 [4 5 6]
 [7 8 9]] is 16.881943016134134
Max norm of [[1 2 3]
 [4 5 6]
 [7 8 9]] is 9
2-norm of [[1 2 3]
 [4 5 6]
 [7 8 9]] is 16.848103352614213
3-norm of [[1 2 3]
 [4 5 6]
 [7 8 9]] is 16.849535224829065
3.5-norm of [[1 2 3]
 [4 5 6]
 [7 8 9]] is 16.84841243172686
4-norm of [[1 2 3]
 [4 5 6]
 [7 8 9]] is 16.84817145624563
Inf-norm of [[1 2 3]
 [4 5 6]
 [7 8 9]] is 24
